### PR TITLE
Fix mirage theme: startup error

### PR DESCRIPTION
**Pull request by itcreator**

### CODE REVIEW

**Comment by WillPower3309** [comment]
Thanks for the PR! Really appreciate it, do you mind adding some more context around your system? Which distro / version of awesomewm are you using?

**Comment by itcreator** [comment]
I'm using Fedora 5.15.10-100.fc34.x86_64

But it was definitely an issue in Lua code. 
In other theme all works fine

**Comment by itcreator** [comment]
hm...
currently, I can't reproduce a bug

Looks like this pr can me closed

**Comment by WillPower3309** [comment]
Sounds good! Let me know if any issues arise

**Pull request closed without merging**
